name: CI/CD with Docker

on:
  push:
    branches:
      - main 
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Build Docker Image
        run: docker build -t selego-docker:latest . --platform=linux/amd64

      - name: Log into Docker Hub
        run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}

      - name: Tag Docker Image
        run: docker tag selego-docker:latest ${{ secrets.DOCKER_USERNAME }}/selego-docker:latest

      - name: Push Docker Image to Docker Hub
        run: docker push ${{ secrets.DOCKER_USERNAME }}/selego-docker:latest
      - name: Run Tests
        run: docker run --rm -v "$(pwd):/app" -w /app selego-docker:latest npm test